# Generated by Django 5.2.4 on 2025-08-02 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acciones', models.JSONField()),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('descartada', 'Descartada')], max_length=20)),
                ('docente_aprobo', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_creadas', to='usuarios.usuario')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='usuarios.usuario')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.fase')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_modificadas', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstudiante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_atencion', models.FloatField(null=True)),
                ('nota_academica', models.FloatField(null=True)),
                ('estado', models.CharField(choices=[('Listo', 'Listo'), ('Observacion', 'Observación'), ('Refuerzo', 'Refuerzo')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='usuarios.usuario')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.fase')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.nivel')),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.recurso')),
                ('recomendacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='recomendaciones.recomendacionia')),
            ],
        ),
    ]
