# Generated by Django 5.2.4 on 2025-08-03 03:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_options_alter_fase_options_and_more'),
        ('recomendaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialestudiante',
            options={'verbose_name': 'Historial Estudiante', 'verbose_name_plural': 'Historiales Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='recomendacionia',
            options={'verbose_name': 'Recomendación IA', 'verbose_name_plural': 'Recomendaciones IA'},
        ),
        migrations.AlterField(
            model_name='historialestudiante',
            name='estado',
            field=models.CharField(choices=[('Listo', 'Listo'), ('Observacion', 'Observación'), ('Refuerzo', 'Refuerzo')], default='Observacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialestudiante',
            name='nota_academica',
            field=models.FloatField(blank=True, help_text='Nota académica en porcentaje (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='historialestudiante',
            name='recurso',
            field=models.ForeignKey(blank=True, help_text='Recurso asociado (opcional, derivable de fase)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.recurso'),
        ),
        migrations.AlterField(
            model_name='historialestudiante',
            name='score_atencion',
            field=models.FloatField(blank=True, help_text='Puntuación de atención en porcentaje (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='recomendacionia',
            name='acciones',
            field=models.JSONField(help_text="Datos JSON con acciones recomendadas (e.g., {'tarea': 'revisar', 'duracion': 30})"),
        ),
        migrations.AlterField(
            model_name='recomendacionia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('descartada', 'Descartada')], default='pendiente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='historialestudiante',
            unique_together={('estudiante', 'fase')},
        ),
    ]
