# Generated by Django 5.2.4 on 2025-08-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil Usuario', 'verbose_name_plural': 'Perfiles Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Especialidad del usuario (opcional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='matricula',
            field=models.CharField(blank=True, help_text='Número de matrícula del estudiante (opcional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Correo electrónico único del usuario', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('docente', 'Docente'), ('estudiante', 'Estudiante')], default='estudiante', help_text='Rol del usuario en el sistema', max_length=20),
        ),
    ]
