# Generated by Django 5.2.4 on 2025-08-02 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionMonitoreo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(null=True)),
                ('duracion', models.DurationField(null=True)),
                ('score_atencion', models.FloatField(null=True)),
                ('patrones', models.JSONField(null=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_monitoreo', to='usuarios.usuario')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.fase')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionVisual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_atencion', models.FloatField()),
                ('patrones', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_visuales', to='usuarios.usuario')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.fase')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.recurso')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.sesionmonitoreo')),
            ],
        ),
    ]
