# Generated by Django 5.2.4 on 2025-08-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencionvisual',
            old_name='score_atencion',
            new_name='desviacion_mirada',
        ),
        migrations.RemoveField(
            model_name='atencionvisual',
            name='patrones',
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='cierre_ojos',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
