# Generated by Django 5.2.4 on 2025-08-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_rename_score_atencion_atencionvisual_desviacion_mirada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencionvisual',
            options={'verbose_name': 'Atención Visual', 'verbose_name_plural': 'Atenciones Visuales'},
        ),
        migrations.RemoveField(
            model_name='atencionvisual',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='atencionvisual',
            name='recurso',
        ),
        migrations.AlterField(
            model_name='atencionvisual',
            name='cierre_ojos',
            field=models.BooleanField(default=False, help_text='Indica si los ojos estuvieron cerrados'),
        ),
        migrations.AlterField(
            model_name='atencionvisual',
            name='desviacion_mirada',
            field=models.FloatField(help_text='Desviación en grados (0-90)'),
        ),
        migrations.AlterField(
            model_name='sesionmonitoreo',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesionmonitoreo',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesionmonitoreo',
            name='patrones',
            field=models.JSONField(blank=True, help_text="Datos JSON con patrones de atención (e.g., {'frecuencia': 5, 'tipo': 'visual'})", null=True),
        ),
        migrations.AlterField(
            model_name='sesionmonitoreo',
            name='score_atencion',
            field=models.FloatField(blank=True, help_text='Puntuación de atención entre 0 y 100', null=True),
        ),
    ]
