# Generated by Django 5.2.4 on 2025-08-04 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0003_alter_atencionvisual_options_and_more'),
        ('cursos', '0003_alter_curso_options_alter_fase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencionvisual',
            options={'verbose_name': 'Atención Visual'},
        ),
        migrations.RemoveField(
            model_name='atencionvisual',
            name='cierre_ojos',
        ),
        migrations.RemoveField(
            model_name='atencionvisual',
            name='desviacion_mirada',
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.fase'),
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='patrones',
            field=models.JSONField(blank=True, help_text="Patrones detectados: {'desviacion_gaze': 0.4, 'cierre_ojos': 0.3, ...}", null=True),
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.recurso'),
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='score_atencion',
            field=models.FloatField(blank=True, help_text='Puntaje global de atención (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='atencionvisual',
            name='estudiante',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'estudiante'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_visuales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atencionvisual',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atencion.sesionmonitoreo'),
        ),
        migrations.AlterField(
            model_name='sesionmonitoreo',
            name='patrones',
            field=models.JSONField(blank=True, help_text="Datos JSON con patrones de atención (e.g., {'desviacion_gaze': 0.4, 'cierre_ojos': 0.3, ...})", null=True),
        ),
    ]
