# Generated by Django 5.2.4 on 2025-08-14 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0004_alter_atencionvisual_options_and_more'),
        ('cursos', '0004_recurso_duracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.recurso')),
            ],
            options={
                'unique_together': {('estudiante', 'recurso')},
            },
        ),
    ]
