# Generated by Django 5.2.9 on 2025-12-06 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0005_notaacademica'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionvisual',
            name='ear',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='mar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='nivel_atencion',
            field=models.CharField(blank=True, help_text='Nivel de atención calculado (Alta/Media/Baja, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='roll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en el que se capturó este frame'),
        ),
        migrations.AddField(
            model_name='atencionvisual',
            name='yaw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atencionvisual',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_atencion', to='atencion.sesionmonitoreo'),
        ),
    ]
