# Generated by Django 5.2.4 on 2025-08-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_creados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_docente', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_modificados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='fase',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fases_creadas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='fase',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fases_modificadas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveles_creados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveles_modificados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='fase',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.nivel'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_creados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.fase'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_modificados', to='usuarios.usuario'),
        ),
    ]
