# Generated by Django 5.2.4 on 2025-08-03 03:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='fase',
            options={'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='recurso',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='umbral_nota',
            field=models.FloatField(default=70.0, help_text='Umbral de aprobación en porcentaje (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='orden',
            field=models.IntegerField(help_text='Orden del nivel dentro del curso (mínimo 1)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(help_text='Tamaño máximo: 50MB', max_length=255, upload_to='recursos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'pdf', 'docx', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='nota_maxima',
            field=models.FloatField(default=100.0, help_text='Nota máxima en porcentaje (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together={('nivel', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('estudiante', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='nivel',
            unique_together={('curso', 'orden')},
        ),
    ]
