# Generated by Django 5.2.4 on 2025-08-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_options_alter_fase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, help_text='Duración del recurso en segundos (obligatorio para recursos evaluables y monitoreables)', null=True),
        ),
    ]
