# Generated by Django 5.2.5 on 2025-08-27 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_recurso_duracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'ordering': ['nivel', 'orden'], 'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fase',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fase',
            name='orden',
            field=models.IntegerField(default=1, help_text='Orden de la fase dentro del nivel (mínimo 1)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together={('nivel', 'orden')},
        ),
    ]
